---
title: "A really engaging title"
author:
  - Catherine Wangen:
      email: cwangen@uw.edu
      institute: qerm, safs
      correspondence: true
  - Mark D. Scheuerell:
      email: scheuerl@uw.edu
      institute: wacfwru
      correspondence: true
institute:
  - qerm: Quantitative Ecology and Resource Management, University of Washington, Seattle, WA
  - safs: School of Aquatic and Fishery Sciences, University of Washington, Seattle, WA
  - wacfwru: U.S. Geological Survey Washington Cooperative Fish and Wildlife Research Unit, School of Aquatic and Fishery Sciences, University of Washington, Seattle, WA
output:
  pdf_document:
    highlight: haddock
    pandoc_args:
      - '--lua-filter=scholarly-metadata.lua'
      - '--lua-filter=author-info-blocks.lua'
documentclass: article
geometry: margin=1in
linestretch: 1.1
fontsize: 12pt
header-includes:
  - \usepackage{lineno}
  - \linenumbers
bibliography: "references.bib"
csl: "aslo.csl"
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)

## load {knitcitations}
# library("knitcitations")

## clean out any existing .bib files
# cleanbib()

## set pandoc for formatting
options("citation_format" = "pandoc")
```


# Introduction



# Methods


## Data


## Modeling



# Results



# Discussion



# Acknowledgments



\newpage

# References

\setlength{\parindent}{-0.375in}
\setlength{\leftskip}{0.375in}
\setlength{\parskip}{8pt}
\noindent

```{r}
## create ref cited section
# write.bibtex(file = "references.bib")
```


